name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Black
        uses: psf/black@stable
      - name: Pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        with:
          args: pip install .; pylint src/**/*.py
