name: Python Poetry CI

permissions:
  contents: read

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  black:
    uses: prosegrinder/.github/.github/workflows/poetry-black.yaml@main

  pylint:
    uses: prosegrinder/.github/.github/workflows/poetry-pylint.yaml@main

  mypy:
    uses: prosegrinder/.github/.github/workflows/poetry-mypy.yaml@main

  bandit:
    uses: prosegrinder/.github/.github/workflows/poetry-bandit.yaml@main

  test:
    needs:
      - pylint
      - black
      - mypy
      - bandit
    uses: prosegrinder/.github/.github/workflows/poetry-test.yaml@main

  cz-dry-run:
    needs: test
    uses: prosegrinder/.github/.github/workflows/poetry-cz-dry-run.yaml@main
    secrets:
      VERSION_BUMP_TAG_TOKEN: "${{ secrets.VERSION_BUMP_TAG_TOKEN }}"
